[pyprland]
plugins = ["scratchpads"]

[scratchpads.kitty]
animation = "fromTop"
command = "kitty --title FloatingKitty"
class = "kitty-dropterm"  # check: hyprctl clients | grep class
state = "floating"
size = "60% 50%"  # size of the window relative to the screen size
unfocus = "hide"
skip_windowrules = ["aspect", "workspace"]

